global:
  scrape_interval:     5s # By default, scrape targets every 15 seconds.
  evaluation_interval: 5s # By default, scrape targets every 15 seconds.
  # external_labels:
      # monitor: 'my-project'

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'app-prometheus-exporter'
    static_configs:
      - targets: ['app:8000']
  
  - job_name: prometheus_scrapper
    static_configs:
    - targets:
      - locust-metrics-exporter:9646
