{
 "title": "Meetings app new",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Locust test status",
   "type": "status-history",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "locust_running", "legendFormat": "Status" }
   ]
  },
  {
   "title": "Infrastructure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
     "targets": [
      { "expr": "process_cpu_seconds_total", "legendFormat": "{{__name__}}_{{instance}}" }
     ]
    }
   ]
  },
  {
   "title": "Locust",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Meetings locust errors",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "sum(locust_errors) by (method, name, error)",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "POST-/meetings/-HIST_RESP_TIME_DIST",
     "type": "histogram",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "locust_requests_avg_response_time{method=\"POST\", name=\"/meetings/\"}",
       "legendFormat": "{{method}}-{{name}}"
      }
     ]
    },
    {
     "title": "Requests thrown",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 5, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "locust_requests_num_requests{method=~\"\"}"
      }
     ]
    },
    {
     "title": "Locust workers connected",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "locust_workers_count", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Locust outgoing http requests response time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "locust_requests_avg_response_time",
       "legendFormat": "{{method}}-{{name}}"
      }
     ]
    },
    {
     "title": "GET-/meetings/{id}-HIST_RESP_TIME_DIST",
     "type": "histogram",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "locust_requests_avg_response_time{method=\"GET\", name=\"/meetings/{id}\"}",
       "legendFormat": "{{method}}-{{name}}"
      }
     ]
    },
    {
     "title": "Locust status",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "locust_running", "legendFormat": "{{label_name}}" }
     ]
    },
    {
     "title": "Locust outgoing requests / min",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "req/min" } },
     "targets": [
      {
       "expr": "rate(locust_requests_num_requests[1m])",
       "legendFormat": "{{method}}-{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache items",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
     "targets": [
      { "expr": "meetings_find_cache_items", "legendFormat": "{{__name__}}" },
      { "expr": "meetings_by_id_cache_items", "legendFormat": "{{__name__}}" }
     ]
    },
    {
     "title": "Cache hits",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 11 },
     "targets": [
      { "expr": "meetings_find_cache_hits_total", "legendFormat": "{{__name__}}" },
      {
       "expr": "meetings_by_id_cache_hits_total",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Cache misses",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 11 },
     "targets": [
      {
       "expr": "meetings_find_cache_misses_total",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "meetings_by_id_cache_misses_total",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Evictions",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 11 },
     "targets": [
      {
       "expr": "meetings_find_cache_evictions_total",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "meetings_by_id_cache_evictions_total",
       "legendFormat": "{{__name__}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Python GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Python uncollectable objects",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "python_gc_objects_uncollectable_total{generation=~\"0|1|2\"}",
       "legendFormat": "generation-{{generation}}"
      }
     ]
    },
    {
     "title": "Python GC Objects Collected rate (min)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 17 },
     "targets": [
      {
       "expr": "rate(python_gc_objects_collected_total[$__rate_interval])",
       "legendFormat": "{{generation}}"
      }
     ]
    },
    {
     "title": "Python GC collections rate (min)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 17 },
     "targets": [
      {
       "expr": "rate(python_gc_collections_total[$__rate_interval])",
       "legendFormat": "{{generation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Concurrency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "TASK_QUEUE",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "targets": [
      { "expr": "task_queue_length", "legendFormat": "{{queue_name}}" }
     ]
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "IN_PROGRESS_HTTP_REQUEST_BY_METHOD",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      { "expr": "starlette_requests_in_progress", "legendFormat": "{{method}}-{{path_template}}" }
     ]
    },
    {
     "title": "AVG_HTTP_REQUESTS_TIME",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "rate(starlette_requests_processing_time_seconds_count[1m])",
       "legendFormat": "{{method}} - {{path_template}}"
      }
     ]
    },
    {
     "title": "SUM_HTTP_REQUESTS_TIME",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "sum_over_time(starlette_requests_processing_time_seconds_sum[1m])",
       "legendFormat": "{{method}} - {{path_template}}"
      }
     ]
    }
   ]
  }
 ]
}